const fs = require("fs");
const path = require("path");

// Update path to correct file
const luaFile = fs.readFileSync(
  path.join(
    __dirname,
    "nvim-web-devicons/lua/nvim-web-devicons/icons-default.lua",
  ),
  "utf8",
);

// Parse the Lua table (simple version)
const iconMap = {};
const matches = luaFile.matchAll(
  /\["([^"]+)"\]\s*=\s*{[^}]*icon\s*=\s*"([^"]+)"[^}]*color\s*=\s*"([^"]+)"/g,
);

for (const match of matches) {
  const [_, ext, icon, color] = match;
  iconMap[ext] = {
    icon,
    color: color.toUpperCase(),
  };
}

// Generate Go code
const goCode = `// Code generated by scripts/generate_icons.js; DO NOT EDIT.
package style

var defaultIcons = map[string]IconDef{
${Object.entries(iconMap)
  .map(
    ([ext, def]) =>
      `    "${ext}": {Icon: "${def.icon}", Color: "${def.color}"},`,
  )
  .join("\n")}
    "": {Icon: "", Color: Reset}, // default
}`;

// Ensure the target directory exists
const targetDir = path.join(__dirname, "../internal/style");
if (!fs.existsSync(targetDir)) {
  fs.mkdirSync(targetDir, { recursive: true });
}

fs.writeFileSync(path.join(targetDir, "generated_icons.go"), goCode);

console.log("Generated icons file successfully!");
